apiVersion: v1
kind: Service
metadata:
  name: media-function-scenes
spec:
  type: LoadBalancer
  selector:
    app: function-scenes
  ports:
    - port: 80
      targetPort: 3000
      protocol: TCP
      name: http